Repository KDT-AiVENGERS/PolarStar_AIModel, pull requests merged in 2023-08, with the labels that each got.

#4 [#3]SETTING: Base folders setting
  .gitignore
  infra/data_module.py
  infra/inference.py
  infra/task_module.py
  main.py
  requirements.txt
  utils/jit_compile.py
Labels: ⭐️FEAT⭐️, P0

#6 [#5]FEAT: endpoint routing, managing model files, jd data files, virtual jd data files, etc
  infra/data_module.py
  main.py
  utils/handling_data.py
  utils/handling_models.py
  utils/jit_compile.py
Labels: ⭐️FEAT⭐️, P0

#12 [#11]FEAT: Minimal functions and endpoint implementation
  .gitignore
  infra/data_module.py
  main.py
  utils/handling_data.py
  utils/handling_models.py
  utils/handling_requests.py
Labels: ⭐️FEAT⭐️, P0

#16 [#13]FIX: fix predicting task to use embedding vector of cls token
  infra/task_module.py
  utils/handling_requests.py
Labels: ⚡️FIX⚡️, P0

#20 Feature/#19 utils/handling_requests.py의 statistics_extracting함수 작성
  main.py
  utils/handling_requests.py
Labels: ⭐️FEAT⭐️

#24 Fix/#21 QnA기반 mock_JD제작 성능을 올리기 위한 함수 FIX
  utils/handling_data.py
  utils/handling_requests.py
Labels: ⭐️FEAT⭐️, ⚡️FIX⚡️

#23 [#22]FEAT: add uploading endpoint, add check function in init endpoint
  main.py
  utils/handling_data.py
  utils/handling_requests.py
Labels: ⭐️FEAT⭐️, P0

#26 [#25]FIX: CORS setting for all urls
  main.py
Labels: ⚡️FIX⚡️, P0

#28 [#27]FIX: remove [0] for DataSeries
  utils/handling_requests.py
Labels: ⚡️FIX⚡️, P0

#30 [#29]FIX: generage_v_jd function fix
  utils/handling_data.py
Labels: ⚡️FIX⚡️, P0
